//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificationStatu
    {
        public int CertificationStatusID { get; set; }
        public int HumanResourceID { get; set; }
        public int CertificationID { get; set; }
        public System.DateTime CertificationDate { get; set; }
        public bool AcceptableResult { get; set; }
        public string ResultDetail { get; set; }
        public string Comments { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime RecordAdded { get; set; }
        public string RecordAddedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual Certification Certification { get; set; }
        public virtual HumanResource HumanResource { get; set; }
    }
}
