//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeLog
    {
        public int ChangeLogID { get; set; }
        public int ApplicationTableFieldID { get; set; }
        public int RecordID { get; set; }
        public string UserName { get; set; }
        public string BeforeValue { get; set; }
        public string AfterValue { get; set; }
        public System.DateTime ChangeMade { get; set; }
    
        public virtual ApplicationTableField ApplicationTableField { get; set; }
    }
}
