//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewResource
    {
        public int CrewResourceID { get; set; }
        public int CrewID { get; set; }
        public int ResourceID { get; set; }
        public int CrewRoleID { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime RecordAdded { get; set; }
        public string RecordAddedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual Crew Crew { get; set; }
        public virtual CrewRole CrewRole { get; set; }
        public virtual HumanResource HumanResource { get; set; }
    }
}
