//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomField()
        {
            this.CustomFieldSelectionLists = new HashSet<CustomFieldSelectionList>();
        }
    
        public int CustomFieldID { get; set; }
        public int CustomFieldTypeID { get; set; }
        public int ApplicationTableID { get; set; }
        public string Description { get; set; }
        public string UILabel { get; set; }
        public bool IsRequired { get; set; }
        public Nullable<int> RangeMin { get; set; }
        public Nullable<int> RangeMax { get; set; }
        public Nullable<System.DateTime> DateMin { get; set; }
        public Nullable<System.DateTime> DateMax { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime RecordAdded { get; set; }
        public string RecordAddedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual ApplicationTable ApplicationTable { get; set; }
        public virtual CustomFieldType CustomFieldType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomFieldSelectionList> CustomFieldSelectionLists { get; set; }
    }
}
