//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driver()
        {
            this.VehicleInsurancePolicies = new HashSet<VehicleInsurancePolicy>();
            this.DriverMobileAssignements = new HashSet<DriverMobileAssignement>();
            this.DriverVehicles = new HashSet<DriverVehicle>();
            this.RoutePlanResources = new HashSet<RoutePlanResource>();
            this.RoutePlanResources1 = new HashSet<RoutePlanResource>();
            this.RoutePlanResources2 = new HashSet<RoutePlanResource>();
            this.RoutePlanResources3 = new HashSet<RoutePlanResource>();
            this.RoutePlanResources4 = new HashSet<RoutePlanResource>();
            this.RoutePlanResources5 = new HashSet<RoutePlanResource>();
            this.RoutePlanResources6 = new HashSet<RoutePlanResource>();
        }
    
        public int DriverID { get; set; }
        public int HumanResourceID { get; set; }
        public string LicenseState { get; set; }
        public System.DateTime LicenseExpiration { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime RecordAdded { get; set; }
        public string RecordAddedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleInsurancePolicy> VehicleInsurancePolicies { get; set; }
        public virtual HumanResource HumanResource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverMobileAssignement> DriverMobileAssignements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverVehicle> DriverVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutePlanResource> RoutePlanResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutePlanResource> RoutePlanResources1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutePlanResource> RoutePlanResources2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutePlanResource> RoutePlanResources3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutePlanResource> RoutePlanResources4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutePlanResource> RoutePlanResources5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutePlanResource> RoutePlanResources6 { get; set; }
    }
}
