//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTS.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSTSEntities : DbContext
    {
        public MSTSEntities()
            : base("name=MSTSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CostProfitCenter> CostProfitCenters { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientBillingEntity> ClientBillingEntities { get; set; }
        public virtual DbSet<ClientManagementUnit> ClientManagementUnits { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ClientLocationAliasType> ClientLocationAliasTypes { get; set; }
        public virtual DbSet<CustomField> CustomFields { get; set; }
        public virtual DbSet<CustomFieldSelectionList> CustomFieldSelectionLists { get; set; }
        public virtual DbSet<CustomFieldType> CustomFieldTypes { get; set; }
        public virtual DbSet<ManagementUnit> ManagementUnits { get; set; }
        public virtual DbSet<ResourceType> ResourceTypes { get; set; }
        public virtual DbSet<RouteClassification> RouteClassifications { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<VehicleType> VehicleTypes { get; set; }
        public virtual DbSet<MobileUnit> MobileUnits { get; set; }
        public virtual DbSet<VehicleDetail> VehicleDetails { get; set; }
        public virtual DbSet<VehicleInsurancePolicy> VehicleInsurancePolicies { get; set; }
        public virtual DbSet<ActionTrack> ActionTracks { get; set; }
        public virtual DbSet<ApplicationTable> ApplicationTables { get; set; }
        public virtual DbSet<ApplicationTableField> ApplicationTableFields { get; set; }
        public virtual DbSet<ChangeLog> ChangeLogs { get; set; }
        public virtual DbSet<ClientAddress> ClientAddresses { get; set; }
        public virtual DbSet<ClientLocationAlia> ClientLocationAlias { get; set; }
        public virtual DbSet<PhysicalLocation> PhysicalLocations { get; set; }
        public virtual DbSet<Certification> Certifications { get; set; }
        public virtual DbSet<CertificationStatu> CertificationStatus { get; set; }
        public virtual DbSet<Crew> Crews { get; set; }
        public virtual DbSet<CrewResource> CrewResources { get; set; }
        public virtual DbSet<CrewRole> CrewRoles { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<DriverMobileAssignement> DriverMobileAssignements { get; set; }
        public virtual DbSet<DriverVehicle> DriverVehicles { get; set; }
        public virtual DbSet<HumanResource> HumanResources { get; set; }
        public virtual DbSet<RoutePlan> RoutePlans { get; set; }
        public virtual DbSet<RoutePlanFamily> RoutePlanFamilies { get; set; }
        public virtual DbSet<RoutePlanResource> RoutePlanResources { get; set; }
        public virtual DbSet<CostComponentUnit> CostComponentUnits { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductTask> ProductTasks { get; set; }
        public virtual DbSet<SurchargeDiscount> SurchargeDiscounts { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaskCost> TaskCosts { get; set; }
        public virtual DbSet<ManagementEntity> ManagementEntities { get; set; }
        public virtual DbSet<ManagementEntityLevel> ManagementEntityLevels { get; set; }
    }
}
