//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutePlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoutePlan()
        {
            this.RoutePlanResources = new HashSet<RoutePlanResource>();
        }
    
        public int RoutePlanID { get; set; }
        public string Description { get; set; }
        public int RoutePlanFamilyID { get; set; }
        public string RoutePlanState { get; set; }
        public int UTCOffset { get; set; }
        public bool IsScheduled { get; set; }
        public int OriginationPhysicalLocationID { get; set; }
        public System.TimeSpan EstimatedLocalStartTime { get; set; }
        public bool IsDriverCheckInRequired { get; set; }
        public int DriverCheckInMinutesBeforeStartTime { get; set; }
        public bool IsAbleToStartEarly { get; set; }
        public int EarliestStartTimeMinutes { get; set; }
        public int LateStartTimeThresholdInMinutes { get; set; }
        public bool IsFedByASN { get; set; }
        public Nullable<System.TimeSpan> ASNCutoffTime { get; set; }
        public int TerminationPhysicalLocationID { get; set; }
        public System.TimeSpan EstimatedLocalEndTime { get; set; }
        public int EndTimeAdditionalDayCount { get; set; }
        public int RequiredVehicleTypeID { get; set; }
        public int RouteClassificationID { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime RecordAdded { get; set; }
        public string RecordAddedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual RouteClassification RouteClassification { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual PhysicalLocation PhysicalLocation { get; set; }
        public virtual PhysicalLocation PhysicalLocation1 { get; set; }
        public virtual RoutePlanFamily RoutePlanFamily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutePlanResource> RoutePlanResources { get; set; }
    }
}
