//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutePlanResource
    {
        public int RoutePlanResourceID { get; set; }
        public int RoutePlanID { get; set; }
        public bool IsCrewRoute { get; set; }
        public Nullable<int> DriverIDSunday { get; set; }
        public Nullable<int> DriverIDMonday { get; set; }
        public Nullable<int> DriverIDTuesday { get; set; }
        public Nullable<int> DriverIDWednesday { get; set; }
        public Nullable<int> DriverIDThursday { get; set; }
        public Nullable<int> DriverIDFriday { get; set; }
        public Nullable<int> DriverIDSaturday { get; set; }
        public Nullable<int> CrewIDSunday { get; set; }
        public Nullable<int> CrewIDMonday { get; set; }
        public Nullable<int> CrewIDTuesday { get; set; }
        public Nullable<int> CrewIDWednesday { get; set; }
        public Nullable<int> CrewIDThursday { get; set; }
        public Nullable<int> CrewIDFriday { get; set; }
        public Nullable<int> CrewIDSaturday { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime RecordAdded { get; set; }
        public string RecordAddedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual Crew Crew { get; set; }
        public virtual Crew Crew1 { get; set; }
        public virtual Crew Crew2 { get; set; }
        public virtual Crew Crew3 { get; set; }
        public virtual Crew Crew4 { get; set; }
        public virtual Crew Crew5 { get; set; }
        public virtual Crew Crew6 { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Driver Driver1 { get; set; }
        public virtual Driver Driver2 { get; set; }
        public virtual Driver Driver3 { get; set; }
        public virtual Driver Driver4 { get; set; }
        public virtual Driver Driver5 { get; set; }
        public virtual Driver Driver6 { get; set; }
        public virtual RoutePlan RoutePlan { get; set; }
    }
}
