//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleInsurancePolicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleInsurancePolicy()
        {
            this.VehicleDetails = new HashSet<VehicleDetail>();
        }
    
        public int VehicleInsurancePolicyID { get; set; }
        public int DriverID { get; set; }
        public string InsuranceCompany { get; set; }
        public string PolicyNumber { get; set; }
        public System.DateTime OriginalEffectiveCoverageDate { get; set; }
        public System.DateTime CurrentCoverageExpirationDate { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime RecordAdded { get; set; }
        public string RecordAddedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleDetail> VehicleDetails { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
